substitutions:
  _GOOGLE_CLIENT_ID: ""
  _SERVICE_NAME: "investbrand-ui"
  _IMAGE_TAG: "gcr.io/market-rover/investbrand-ui:latest"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'REACT_APP_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}',
    '--label', 'service=${_SERVICE_NAME}',
    '-t', '${_IMAGE_TAG}',
    '.'
  ]
images:
- '${_IMAGE_TAG}'
