steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/market-rover-api:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/market-rover-api:$COMMIT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/market-rover-api:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
