"""
Monthly Issue Report Generator
----------------------------
Aggregates open issues and creates a summary report as a new issue.
Designed to be run via GitHub Actions on a monthly schedule.
"""
import os
import sys
import datetime
import requests
import json

# Add project root to path to verify config import works as requested
sys.path.append(os.getcwd())

try:
    import config
except ImportError:
    print("Warning: Could not import config (ModuleNotFoundError). PYTHONPATH might be missing.", file=sys.stderr)
    # We continue anyway since config might not be strictly needed for this specific logic,
    # but the user specifically asked to fix this error, so we want it to succeed.
    sys.exit(1)

def get_repo_info():
    """Extract owner/repo from GITHUB_REPOSITORY env var."""
    repo_full_name = os.environ.get("GITHUB_REPOSITORY")
    if not repo_full_name:
        print("Error: GITHUB_REPOSITORY environment variable not set.")
        sys.exit(1)
    return repo_full_name

def get_issues(repo_full_name, token):
    """Fetch open issues from GitHub API."""
    url = f"https://api.github.com/repos/{repo_full_name}/issues"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    params = {
        "state": "open",
        "per_page": 100 
    }
    
    response = requests.get(url, headers=headers, params=params)
    if response.status_code != 200:
        print(f"Error fetching issues: {response.status_code} - {response.text}")
        sys.exit(1)
        
    return response.json()

def generate_report_body(issues):
    """Format issues into a markdown report."""
    now = datetime.datetime.now()
    month_str = now.strftime("%B %Y")
    date_str = now.strftime("%Y-%m-%d")
    
    if not issues:
        return f"No open issues found as of {date_str}."

    report = [f"# Monthly Issue Report - {month_str}\n"]
    report.append(f"### Open Issues Summary (as of {date_str})\n")
    report.append("| # | Title | Author | Labels |")
    report.append("|---|---|---|---|")
    
    count = 0
    for issue in issues:
        # Skip pull requests (which are also 'issues' in API)
        if "pull_request" in issue:
            continue
            
        number = issue["number"]
        title = issue["title"]
        author = issue["user"]["login"]
        labels = ", ".join([l["name"] for l in issue["labels"]])
        url = issue["html_url"]
        
        # Link the title to the issue
        title_link = f"[{title}]({url})"
        
        report.append(f"| #{number} | {title_link} | {author} | {labels} |")
        count += 1
        
    if count == 0:
        return f"No open issues (excluding PRs) found as of {date_str}."

    report.append(f"\n**Total Open Issues:** {count}")
    report.append("\n*Generated by Market Rover Monthly Report Bot*")
    
    return "\n".join(report)

def create_issue(repo_full_name, token, title, body):
    """Create a new issue with the report."""
    url = f"https://api.github.com/repos/{repo_full_name}/issues"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {
        "title": title,
        "body": body,
        "labels": ["monthly-report"]
    }
    
    response = requests.post(url, headers=headers, data=json.dumps(data))
    if response.status_code == 201:
        print(f"Successfully created report issue: {response.json()['html_url']}")
    else:
        print(f"Error creating issue: {response.status_code} - {response.text}")
        sys.exit(1)

def main():
    print("Starting Monthly Issue Report generation...")
    
    # 1. Validation
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("Error: GITHUB_TOKEN environment variable not set.")
        sys.exit(1)
        
    repo_full_name = get_repo_info()
    print(f"Repository: {repo_full_name}")
    
    # 2. Fetch Issues
    issues = get_issues(repo_full_name, token)
    print(f"Fetched {len(issues)} items (issues + PRs).")
    
    # 3. Generate Report
    report_body = generate_report_body(issues)
    
    # 4. Create New Issue
    now = datetime.datetime.now()
    month_str = now.strftime("%B %Y")
    issue_title = f"Monthly Issue Report: {month_str}"
    
    create_issue(repo_full_name, token, issue_title, report_body)
    print("Done.")

if __name__ == "__main__":
    main()
